local background = "#e7e7e7"
local surface = "#e1e1e1"
local selection = "#c3c7c9"

return {
  contrast = "hard",
  palette_overrides = {
    bright_red = "#923f3a",
    bright_green = "#2b4024",
    bright_yellow = "#412e05",
    bright_blue = "#4261a5",
    bright_purple = "#6f4450",
    bright_aqua = "#31452a",
    bright_orange = "#793a06",
    neutral_red = "#f42d25",
    neutral_green = "#5c5b0c",
    neutral_yellow = "#634409",
    neutral_blue = "#3c7678",
    neutral_purple = "#9d5677",
    neutral_aqua = "#3f6241",
    neutral_orange = "#ab4909",
    dark_red = "#ff717b",
    dark_green = "#7f8852",
    dark_aqua = "#98a57d",
    dark_red_hard = "#ff6675",
    dark_green_hard = "#849057",
    dark_aqua_hard = "#9ab284",
  },
  overrides = {
    MatchParen = { bold = true, underline = true, fg = "#543f1d", bg = selection },
    Normal = { bg = background },
    NormalFloat = { bg = background },
    SignColumn = { bg = background },
    StatusLine = { bg = background },
    StatusLineNC = { bg = background },
    GitSignsAdd = { fg = "#404523", bg = background },
    GitSignsChange = { fg = "#543f1d", bg = background },
    GitSignsDelete = { fg = "#923f3a", bg = background },
    GitSignsTopdelete = { fg = "#923f3a", bg = background },
    GitSignsChangedelete = { fg = "#543f1d", bg = background },
    GitSignsUntracked = { fg = "#374f4a", bg = background },
    GitSignsStagedAdd = { fg = "#6e7b44", bg = background },
    GitSignsStagedChange = { fg = "#90723c", bg = background },
    GitSignsStagedDelete = { fg = "#e16963", bg = background },
    GitSignsStagedTopdelete = { fg = "#e16963", bg = background },
    GitSignsStagedChangedelete = { fg = "#90723c", bg = background },
    LineNr = { bg = background },
    CursorLineNr = { bg = background },
    CursorLine = { bg = surface },
    FoldColumn = { bg = background },
    DiffAdd = { bg = "#bbe5a0" },
    DiffChange = { bg = "#e3e3c2" },
    DiffDelete = { bg = "#ffc7c7" },
  },
}
