local background = "#e7e7e7"
local surface = "#e1e1e1"
local selection = "#c3c7c9"

return {
  contrast = "hard",
  palette_overrides = {
    bright_red = "#ea6962",
    neutral_red = "#ea6962",
    faded_red = "#ea6962",
    bright_green = "#8ec97c",
    neutral_green = "#8ec97c",
    faded_green = "#8ec97c",
    bright_yellow = "#d8a657",
    neutral_yellow = "#d8a657",
    faded_yellow = "#d8a657",
    bright_blue = "#5b84de",
    neutral_blue = "#5b84de",
    faded_blue = "#5b84de",
    bright_purple = "#d3869b",
    neutral_purple = "#d3869b",
    faded_purple = "#d3869b",
    bright_aqua = "#8ec07c",
    neutral_aqua = "#8ec07c",
    faded_aqua = "#8ec07c",
    bright_orange = "#e78a4e",
    neutral_orange = "#e78a4e",
    faded_orange = "#e78a4e",
  },
  overrides = {
    MatchParen = { bold = true, underline = true, fg = "#d8a657", bg = selection },
    Normal = { bg = background },
    NormalFloat = { bg = background },
    SignColumn = { bg = background },
    StatusLine = { bg = background },
    StatusLineNC = { bg = background },
    GitSignsAdd = { fg = "#6fae70", bg = background },
    GitSignsChange = { fg = "#b57614", bg = background },
    GitSignsDelete = { fg = "#ea6962", bg = background },
    GitSignsTopdelete = { fg = "#ea6962", bg = background },
    GitSignsChangedelete = { fg = "#b57614", bg = background },
    GitSignsUntracked = { fg = "#5b84de", bg = background },
    GitSignsStagedAdd = { fg = "#5f8b50", bg = background },
    GitSignsStagedChange = { fg = "#9d6b0f", bg = background },
    GitSignsStagedDelete = { fg = "#b85751", bg = background },
    GitSignsStagedTopdelete = { fg = "#b85751", bg = background },
    GitSignsStagedChangedelete = { fg = "#9d6b0f", bg = background },
    LineNr = { bg = background },
    CursorLineNr = { bg = background },
    CursorLine = { bg = surface },
    FoldColumn = { bg = background },
    DiffAdd = { bg = "#d9e8d2" },
    DiffChange = { bg = "#eee4c7" },
    DiffDelete = { bg = "#f1d6d2" },
  },
}
